routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/login/phone', 'Auth\LoginController@phone')->name('login.phone');
Route::post('/login/phone', 'Auth\LoginController@verify');
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');
Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

Route::group([
	'prefix' => 'adverts',
	'as' => 'adverts.',
	'namespace' => 'Adverts',
], function () {
	Route::get('/show/{advert}', 'AdvertController@show')->name('show');
	Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
	Route::post('/show/{advert}/favorites', 'FavoriteController@add')->name('favorites');
	Route::delete('/show/{advert}/favorites', 'FavoriteController@remove');
	Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
            Route::post('/phone', 'PhoneController@request');
            Route::get('/phone', 'PhoneController@form')->name('phone');
            Route::put('/phone', 'PhoneController@verify')->name('phone.verify');
            Route::post('/phone/auth/', 'PhoneController@auth')->name('phone.auth');
        });
        Route::get('favorites', 'FavoriteController@index')->name('favorites.index');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
        Route::group([
            'prefix' => 'adverts',
            'as' => 'adverts.',
            'namespace' => 'Adverts',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'AdvertController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
            Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
            Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
            Route::put('/{advert}/edit', 'ManageController@edit');
            Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
            Route::post('/{advert}/photos', 'ManageController@photos');
            Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
            Route::post('/{advert}/attributes', 'ManageController@attributes');
            Route::post('/{advert}/send', 'ManageController@send')->name('send');
            Route::post('/{advert}/close', 'ManageController@close')->name('close');
            Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
        });
        Route::group([
            'prefix' => 'banners',
            'as' => 'banners.',
            'namespace' => 'Banners',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'BannerController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/banner/{category}/{region?}', 'CreateController@banner')->name('create.banner');
            Route::post('/create/banner/{category}/{region?}', 'CreateController@store')->name('create.banner.store');
            Route::get('/show/{banner}', 'BannerController@show')->name('show');
            Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
            Route::put('/{banner}/edit', 'BannerController@edit');
            Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
            Route::put('/{banner}/file', 'BannerController@file');
            Route::post('/{banner}/send', 'BannerController@send')->name('send');
            Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
            Route::post('/{banner}/order', 'BannerController@order')->name('order');
            Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
        });
    }
);

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'can:admin-panel'],
	],
	function () {
		Route::post('/ajax/upload/image', 'UploadController@image')->name('ajax.upload.image');
		Route::get('/', 'HomeController@index')->name('home');
		Route::resource('users', 'UsersController');
		Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
		Route::resource('regions', 'RegionController');
		Route::resource('pages', 'PageController');
		Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
			Route::post('/first', 'PageController@first')->name('first');
			Route::post('/up', 'PageController@up')->name('up');
			Route::post('/down', 'PageController@down')->name('down');
			Route::post('/last', 'PageController@last')->name('last');
		});
		Route::group(['prefix' => 'adverts', 'as' => 'adverts.', 'namespace' => 'Adverts'], function () {
			Route::resource('categories', 'CategoryController');
			Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
				Route::post('/first', 'CategoryController@first')->name('first');
				Route::post('/up', 'CategoryController@up')->name('up');
				Route::post('/down', 'CategoryController@down')->name('down');
				Route::post('/last', 'CategoryController@last')->name('last');
				Route::resource('attributes', 'AttributeController')->except('index');
			});
			Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
				Route::get('/', 'AdvertController@index')->name('index');
				Route::get('/{advert}/edit', 'AdvertController@editForm')->name('edit');
				Route::put('/{advert}/edit', 'AdvertController@edit');
				Route::get('/{advert}/photos', 'AdvertController@photosForm')->name('photos');
				Route::post('/{advert}/photos', 'AdvertController@photos');
				Route::get('/{advert}/attributes', 'AdvertController@attributesForm')->name('attributes');
				Route::post('/{advert}/attributes', 'AdvertController@attributes');
				Route::post('/{advert}/moderate', 'AdvertController@moderate')->name('moderate');
				Route::get('/{advert}/reject', 'AdvertController@rejectForm')->name('reject');
				Route::post('/{advert}/reject', 'AdvertController@reject');
				Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
			});
		});
		Route::group(['prefix' => 'banners', 'as' => 'banners.'], function () {
			Route::get('/', 'BannerController@index')->name('index');
			Route::get('/{banner}/show', 'BannerController@show')->name('show');
			Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
			Route::put('/{banner}/edit', 'BannerController@edit');
			Route::post('/{banner}/moderate', 'BannerController@moderate')->name('moderate');
			Route::get('/{banner}/reject', 'BannerController@rejectForm')->name('reject');
			Route::post('/{banner}/reject', 'BannerController@reject');
			Route::post('/{banner}/pay', 'BannerController@pay')->name('pay');
			Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
		});
		Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
			Route::get('/', 'TicketController@index')->name('index');
			Route::get('/{ticket}/show', 'TicketController@show')->name('show');
			Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
			Route::put('/{ticket}/edit', 'TicketController@edit');
			Route::post('{ticket}/message', 'TicketController@message')->name('message');
			Route::post('/{ticket}/close', 'TicketController@close')->name('close');
			Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
			Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
			Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
		});
	}
);

Route::get('/ajax/regions', 'Ajax\RegionController@get')->name('ajax.regions');

app/Models/Adverts/Attribute.php
<?php

namespace App\Models\Adverts;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Advert\Attribute
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute query()
 * @mixin \Eloquent
 * @property int $id
 * @property int $category_id
 * @property string $name
 * @property string $type
 * @property int $required
 * @property array $variants
 * @property int $sort
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereCategoryId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereRequired($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereSort($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereType($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Adverts\Attribute whereVariants($value)
 */
class Attribute extends Model
{
    protected $fillable = ['name', 'type', 'required', 'default', 'variants', 'sort'];
    
    public const TYPE_STRING = 'string';
    public const TYPE_INTEGER = 'integer';
    public const TYPE_FLOAT = 'float';
    
    protected $table = 'advert_attributes';
    
    public $timestamps = false;
    
    protected $casts = [
        'variants' => 'array'
    ];
    
    public static function typesList(): array
    {
        return [
            self::TYPE_STRING => 'String',
            self::TYPE_INTEGER => 'Integer',
            self::TYPE_FLOAT => 'Float',
        ];
    }
    
    public function isString(): bool
    {
        return $this->type === self::TYPE_STRING;
    }
    
    public function isInteger(): bool
    {
        return $this->type === self::TYPE_INTEGER;
    }
    
    public function isFloat(): bool
    {
        return $this->type === self::TYPE_FLOAT;
    }
    
    public function isNumber():bool
    {
    	return $this->isInteger() || $this->isFloat();
    }
    
    public function isSelect(): bool
    {
        return count($this->variants) > 0;
    }
}

app/Http/Controllers/Admin/Adverts/AttributeController.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

use App\Http\Requests\Admin\Adverts\AttributeRequest;
use App\Models\Adverts\Attribute;
use App\Models\Adverts\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;


class AttributeController extends Controller
{
    
    public function create(Category $category)
    {
        $types = Attribute::typesList();
        
        return view('admin.adverts.categories.attributes.create', compact('category', 'types'));
    }
    
    public function store(AttributeRequest $request, Category $category)
    {
        $attribute = $category->attributes()->create([
            'name' => $request['name'],
            'type' => $request['type'],
            'required' => (bool)$request['required'],
            'variants' => array_map('trim', preg_split('#[\r\n]+#', $request['variants'])),
            'sort' => $request['sort']
        ]);
        return redirect()->route('admin.adverts.categories.attributes.show', [$category, $attribute]);
    }
    
    public function show(Category $category, Attribute $attribute)
    {
        $types = Attribute::typesList();
        
        return view('admin.adverts.categories.attributes.edit', compact('category', 'attribute', 'types'));
    }
    
    public function edit(Category $category)
    {
        $parents = Category::defaultOrder()->withDepth()->get();
        
        return view('admin.adverts.categories.edit', compact('category', 'parents'));
    }
    
    public function update(AttributeRequest $request, Category $category, Attribute $attribute)
    {
        $category->attributes()->findOrFail($attribute->id)->update([
            'name' => $request['name'],
            'type' => $request['type'],
            'required' => (bool)$request['required'],
            'variants' => array_map('trim', preg_split('#[\r\n]+#', $request['variants'])),
            'sort' => $request['sort']
        ]);
        
        return redirect()->route('admin.adverts.categories.show', $category);
    }
    
    public function destroy(Category $category)
    {
        $category->delete();
        
        return redirect()->route('admin.adverts.categories.index');
    }
}

app/Http/Controllers/Admin/Adverts/CategoryController.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

use App\Http\Requests\Admin\Adverts\CategoryRequest;
use App\Models\Adverts\Category;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{

    public function index()
    {
        $categories = Category::defaultOrder()->withDepth()->paginate(30);
        
        return view('admin.adverts.categories.index', compact('categories'));
    }
    
    public function create()
    {
        $parents = Category::defaultOrder()->withDepth()->get();
        
        return view('admin.adverts.categories.create', compact('parents'));
    }
    
    public function store(CategoryRequest $request)
    {
        $category = Category::create([
            'name' => $request['name'],
            'slug' => $request['slug'],
            'parent_id' => $request['parent'],
        ]);
        return redirect()->route('admin.adverts.categories.show', $category);
    }
    
    public function show(Category $category)
    {
        $parentAttributes = $category->parentAttributes();
        $attributes = $category->attributes()->orderBy('sort')->get();
        
        return view('admin.adverts.categories.show', compact('category', 'attributes', 'parentAttributes'));
    }
    
    public function edit(Category $category)
    {
        $parents = Category::defaultOrder()->withDepth()->get();
        
        return view('admin.adverts.categories.edit', compact('category', 'parents'));
    }
    
    public function update(CategoryRequest $request, Category $category)
    {
        $category->update([
            'name' => $request['name'],
            'slug' => $request['slug'],
            'parent_id' => $request['parent'],
        ]);
        
        return redirect()->route('admin.adverts.categories.show', $category);
    }
    
    public function destroy(Category $category)
    {
        $category->delete();
        
        return redirect()->route('admin.adverts.categories.index');
    }
    
    public function first(Category $category)
    {
        if ($first = $category->siblings()->defaultOrder()->first()) {
            $category->insertBeforeNode($first);
        }
        return redirect()->route('admin.adverts.categories.index');
    }
    public function up(Category $category)
    {
        $category->up();
        return redirect()->route('admin.adverts.categories.index');
    }
    public function down(Category $category)
    {
        $category->down();
        return redirect()->route('admin.adverts.categories.index');
    }
    public function last(Category $category)
    {
        if ($last = $category->siblings()->defaultOrder('desc')->first()) {
            $category->insertAfterNode($last);
        }
        return redirect()->route('admin.adverts.categories.index');
    }
}

resources/views/admin/adverts/categories/attributes/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')
    
    <form method="POST" action="{{ route('admin.adverts.categories.attributes.store', $category) }}">
        @csrf
        
        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="sort" class="col-form-label">Sort</label>
            <input id="sort" type="text" class="form-control{{ $errors->has('sort') ? ' is-invalid' : '' }}" name="sort" value="{{ old('sort') }}" required>
            @if ($errors->has('sort'))
                <span class="invalid-feedback"><strong>{{ $errors->first('sort') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="type" class="col-form-label">Type</label>
            <select id="type" class="form-control{{ $errors->has('type') ? ' is-invalid' : '' }}" name="type">
                @foreach ($types as $type => $label)
                    <option value="{{ $type }}"{{ $type == old('type') ? ' selected' : '' }}>{{ $label }}</option>
                @endforeach;
            </select>
            @if ($errors->has('type'))
                <span class="invalid-feedback"><strong>{{ $errors->first('type') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="variants" class="col-form-label">Variants</label>
            <textarea id="variants" type="text" class="form-control{{ $errors->has('sort') ? ' is-invalid' : '' }}" name="variants">{{ old('variants') }}</textarea>
            @if ($errors->has('variants'))
                <span class="invalid-feedback"><strong>{{ $errors->first('variants') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <input type="hidden" name="required" value="0">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="required" {{ old('required') ? 'checked' : '' }}> Required
                </label>
            </div>
            @if ($errors->has('required'))
                <span class="invalid-feedback"><strong>{{ $errors->first('required') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/adverts/categories/attributes/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')
    
    <form method="POST" action="{{ route('admin.adverts.categories.attributes.update', [$category, $attribute]) }}">
        @csrf
        @method('PUT')
        
        <div class="form-group">
            <label for="name" class="col-form-label">Name</label>
            <input id="name" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" name="name" value="{{ old('name', $attribute->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="sort" class="col-form-label">Sort</label>
            <input id="sort" type="text" class="form-control{{ $errors->has('sort') ? ' is-invalid' : '' }}" name="sort" value="{{ old('sort', $attribute->sort) }}" required>
            @if ($errors->has('sort'))
                <span class="invalid-feedback"><strong>{{ $errors->first('sort') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="type" class="col-form-label">Type</label>
            <select id="type" class="form-control{{ $errors->has('type') ? ' is-invalid' : '' }}" name="type">
                @foreach ($types as $type => $label)
                    <option value="{{ $type }}"{{ $type == old('type', $attribute->type) ? ' selected' : '' }}>{{ $label }}</option>
                @endforeach;
            </select>
            @if ($errors->has('type'))
                <span class="invalid-feedback"><strong>{{ $errors->first('type') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="variants" class="col-form-label">Variants</label>
            <textarea id="variants" type="text" class="form-control{{ $errors->has('sort') ? ' is-invalid' : '' }}" name="variants">{{ old('variants', implode("\n", $attribute->variants)) }}</textarea>
            @if ($errors->has('variants'))
                <span class="invalid-feedback"><strong>{{ $errors->first('variants') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <input type="hidden" name="required" value="0">
            <div class="checkbox">
                <label>
                    <input type="checkbox" name="required" {{ old('required', $attribute->required) ? 'checked' : '' }}> Rquired
                </label>
            </div>
            @if ($errors->has('required'))
                <span class="invalid-feedback"><strong>{{ $errors->first('required') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/adverts/categories/attributes/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.adverts.categories._nav')
    
    <div class="d-flex flex-row mb-3 mt-3">
        <a href="{{ route('admin.adverts.categories.attributes.edit', [$category, $attribute]) }}" class="btn btn-primary mr-1">Edit</a>
        <form method="POST" action="{{ route('admin.adverts.categories.attributes.destroy', [$category, $attribute]) }}" class="mr-1">
            @csrf
            @method('DELETE')
            <button class="btn btn-danger">Delete</button>
        </form>
    </div>
    
    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th><td>{{ $category->id }}</td>
        </tr>
        <tr>
            <th>Name</th><td>{{ $category->name }}</td>
        </tr>
        <tr>
            <th>Slug</th><td>{{ $category->slug }}</td>
        </tr>
        <tbody>
        </tbody>
    </table>
@endsection