routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/login/phone', 'Auth\LoginController@phone')->name('login.phone');
Route::post('/login/phone', 'Auth\LoginController@verify');
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');
Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

Route::group([
	'prefix' => 'adverts',
	'as' => 'adverts.',
	'namespace' => 'Adverts',
], function () {
	Route::get('/show/{advert}', 'AdvertController@show')->name('show');
	Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
	Route::post('/show/{advert}/favorites', 'FavoriteController@add')->name('favorites');
	Route::delete('/show/{advert}/favorites', 'FavoriteController@remove');
	Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
            Route::post('/phone', 'PhoneController@request');
            Route::get('/phone', 'PhoneController@form')->name('phone');
            Route::put('/phone', 'PhoneController@verify')->name('phone.verify');
            Route::post('/phone/auth/', 'PhoneController@auth')->name('phone.auth');
        });
        Route::get('favorites', 'FavoriteController@index')->name('favorites.index');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
        Route::group([
            'prefix' => 'adverts',
            'as' => 'adverts.',
            'namespace' => 'Adverts',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'AdvertController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
            Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
            Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
            Route::put('/{advert}/edit', 'ManageController@edit');
            Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
            Route::post('/{advert}/photos', 'ManageController@photos');
            Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
            Route::post('/{advert}/attributes', 'ManageController@attributes');
            Route::post('/{advert}/send', 'ManageController@send')->name('send');
            Route::post('/{advert}/close', 'ManageController@close')->name('close');
            Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
        });
        Route::group([
            'prefix' => 'banners',
            'as' => 'banners.',
            'namespace' => 'Banners',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'BannerController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/banner/{category}/{region?}', 'CreateController@banner')->name('create.banner');
            Route::post('/create/banner/{category}/{region?}', 'CreateController@store')->name('create.banner.store');
            Route::get('/show/{banner}', 'BannerController@show')->name('show');
            Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
            Route::put('/{banner}/edit', 'BannerController@edit');
            Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
            Route::put('/{banner}/file', 'BannerController@file');
            Route::post('/{banner}/send', 'BannerController@send')->name('send');
            Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
            Route::post('/{banner}/order', 'BannerController@order')->name('order');
            Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
        });
    }
);

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'can:admin-panel'],
	],
	function () {
		Route::post('/ajax/upload/image', 'UploadController@image')->name('ajax.upload.image');
		Route::get('/', 'HomeController@index')->name('home');
		Route::resource('users', 'UsersController');
		Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
		Route::resource('regions', 'RegionController');
		Route::resource('pages', 'PageController');
		Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
			Route::post('/first', 'PageController@first')->name('first');
			Route::post('/up', 'PageController@up')->name('up');
			Route::post('/down', 'PageController@down')->name('down');
			Route::post('/last', 'PageController@last')->name('last');
		});
		Route::group(['prefix' => 'adverts', 'as' => 'adverts.', 'namespace' => 'Adverts'], function () {
			Route::resource('categories', 'CategoryController');
			Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
				Route::post('/first', 'CategoryController@first')->name('first');
				Route::post('/up', 'CategoryController@up')->name('up');
				Route::post('/down', 'CategoryController@down')->name('down');
				Route::post('/last', 'CategoryController@last')->name('last');
				Route::resource('attributes', 'AttributeController')->except('index');
			});
			Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
				Route::get('/', 'AdvertController@index')->name('index');
				Route::get('/{advert}/edit', 'AdvertController@editForm')->name('edit');
				Route::put('/{advert}/edit', 'AdvertController@edit');
				Route::get('/{advert}/photos', 'AdvertController@photosForm')->name('photos');
				Route::post('/{advert}/photos', 'AdvertController@photos');
				Route::get('/{advert}/attributes', 'AdvertController@attributesForm')->name('attributes');
				Route::post('/{advert}/attributes', 'AdvertController@attributes');
				Route::post('/{advert}/moderate', 'AdvertController@moderate')->name('moderate');
				Route::get('/{advert}/reject', 'AdvertController@rejectForm')->name('reject');
				Route::post('/{advert}/reject', 'AdvertController@reject');
				Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
			});
		});
		Route::group(['prefix' => 'banners', 'as' => 'banners.'], function () {
			Route::get('/', 'BannerController@index')->name('index');
			Route::get('/{banner}/show', 'BannerController@show')->name('show');
			Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
			Route::put('/{banner}/edit', 'BannerController@edit');
			Route::post('/{banner}/moderate', 'BannerController@moderate')->name('moderate');
			Route::get('/{banner}/reject', 'BannerController@rejectForm')->name('reject');
			Route::post('/{banner}/reject', 'BannerController@reject');
			Route::post('/{banner}/pay', 'BannerController@pay')->name('pay');
			Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
		});
		Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
			Route::get('/', 'TicketController@index')->name('index');
			Route::get('/{ticket}/show', 'TicketController@show')->name('show');
			Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
			Route::put('/{ticket}/edit', 'TicketController@edit');
			Route::post('{ticket}/message', 'TicketController@message')->name('message');
			Route::post('/{ticket}/close', 'TicketController@close')->name('close');
			Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
			Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
			Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
		});
	}
);

Route::get('/ajax/regions', 'Ajax\RegionController@get')->name('ajax.regions');

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\Region
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\Region[] $children
 * @property-read \App\Models\Region $parent
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string $slug
 * @property int|null $parent_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereParentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereSlug($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Region roots()
 */
class Region extends Model
{
	
	protected $fillable = ['name', 'slug', 'parent_id'];
	
	public function getPath(): string
	{
		return ($this->parent ? $this->parent->getPath() . '/' : '') . $this->slug;
	}
	
	public function getAddress(): string
	{
		return ($this->parent ? $this->parent->getAddress() . ', ' : '') . $this->name;
	}
    
    public function parent()
    {
        return $this->belongsTo(static::class, 'parent_id', 'id');
    }
    
    public function children()
    {
        return $this->hasMany(static::class, 'parent_id', 'id');
    }
    
    public function scopeRoots(Builder $query)
    {
        return $query->where('parent_id', null);
    }
}

app/Http/Controllers/Admin/RegionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\Region;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RegionController extends Controller
{
    public function index()
    {
        $regions = Region::where('parent_id', null)->orderBy('name')->paginate(20);
        
        return view('admin.regions.index', compact('regions'));
    }
    
    public function create(Request $request)
    {
        $parent = null;
        
        if ($request->get('parent')) {
            $parent = Region::findOrFail($request->get('parent'));
        }
        
        return view('admin.regions.create', compact('parent'));
    }
    
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255|unique:regions,name,NULL,id,parent_id,' . ($request['parent'] ?: 'NULL'),
            'slug' => 'required|string|max:255|unique:regions,slug,NULL,id,parent_id,' . ($request['parent'] ?: 'NULL'),
            'parent' => 'exists:regions,id'
        ]);
        $region = Region::create([
            'name' => $request['name'],
            'slug' => $request['slug'],
            'parent_id' => $request['parent'],
        ]);
        return redirect()->route('admin.regions.show', $region);
    }
    
    public function show(Region $region)
    {
        $regions = $region->children()->orderBy('name')->get();
        
        return view('admin.regions.show', compact('region', 'regions'));
    }
    
    public function edit(Region $region)
    {
        return view('admin.regions.edit', compact('region'));
    }
    
    public function update(Request $request, Region $region)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255|unique:regions,name,'
                . $region->id . ',id,parent_id,' . $region->parent_id,
            'slug' => 'required|string|max:255|unique:regions,slug,'
                . $region->id . ',id,parent_id,' . $region->parent_id,
        ]);
        $region->update([
            'name' => $request['name'],
            'slug' => $request['slug'],
        ]);
        return redirect()->route('admin.regions.show', $region);
    }
    
    public function destroy(Region $region)
    {
        $region->delete();
    
        return redirect()->route('admin.regions.index', $region);
    }
}

app/Http/Controllers/Ajax/RegionController.php
<?php

namespace App\Http\Controllers\Ajax;

use App\Models\Region;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class RegionController extends Controller
{
    public function get(Request $request): array
    {
    	$parent = $request->get('parent') ?: null;
    	
    	return Region::where('parent_id', $parent)
		    ->orderBy('name')
		    ->select('id','name')
		    ->get()
		    ->toArray();
    }
}

resources/views/admin/regions/_list.blade.php
<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>SLUG</th>
    </tr>
    </thead>
    <tbody>
    
    @foreach($regions as $region)
        <tr>
            <td>{{ $region->id }}</td>
            <td><a href="{{ route('admin.regions.show', $region) }}">{{ $region->name }}</a></td>
            <td>{{ $region->slug }}</td>
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/admin/regions/_nav.blade.php
<ul class="nav nav-tabs md-3">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.home') }}">Dashboard</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.users.index') }}">Users</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{{ route('admin.regions.index') }}">Regions</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.adverts.categories.index') }}">Category</a>
    </li>
</ul>

resources/views/admin/regions/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.regions._nav')
    <form method="POST" action="{{ route('admin.regions.store', ['parent' => $parent ? $parent->id : null]) }}">
        @csrf
    
        <div class="form-group">
            <label for="" class="col-form-label">Name</label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
            name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
    
        <div class="form-group">
            <label for="" class="col-form-label">Slug</label>
            <input id="slug" type="slug" class="form-control{{ $errors->has('slug') ? ' is-invalid' : '' }}"
                   name="slug" value="{{ old('slug') }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong>
                </span>
            @endif
        </div>
    
        <div class="form-group">
            <button class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/regions/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.regions._nav')
    
    <form method="POST" action="{{ route('admin.regions.update', $region) }}">
        @csrf
        @method('PUT')
        
        <div class="form-group">
            <label for="" class="col-form-label">Name</label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                   name="name" value="{{ old('name', $region->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="slug" class="col-form-label">SLUG</label>
            <input id="slug" type="slug" class="form-control {{ $errors->has('slug') ? 'is-invalid' : '' }}"
                   name="slug" value="{{ old('slug', $region->slug) }}" required>
            @if ($errors->has('slug'))
                <span class="invalid-feedback"><strong>{{ $errors->first('slug') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <button class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/regions/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.regions._nav')

    <p><a href="{{ route('admin.regions.create') }}" class="btn btn-success mr-1 mt-3">Add region</a></p>
    
    @include('admin.regions._list', ['regions' => $regions])

    {{ $regions->links() }}
@endsection

resources/views/admin/regions/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.regions._nav')
    
    <div class="d-flex flex-row mb-3 mt-3">
        <a href="{{ route('admin.regions.create', ['parent' => $region->id]) }}" class="btn btn-success mr-1">Add subregion</a>
        <a href="{{ route('admin.regions.edit', $region) }}" class="btn btn-primary mr-1">Edit</a>
            <form method="POST" action="{{ route('admin.regions.update', $region) }}" class="mr-1">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Delete</button>
            </form>
    </div>
    
    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th>
            <td>{{ $region->id }}</td>
        </tr>
        <tr>
            <th>NAME</th>
            <td>{{ $region->name }}</td>
        </tr>
        <tr>
            <th>SLUG</th>
            <td>{{ $region->slug }}</td>
        </tr>
        </tbody>
    </table>

    @include('admin.regions._list', ['regions' => $regions])
@endsection