routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/login/phone', 'Auth\LoginController@phone')->name('login.phone');
Route::post('/login/phone', 'Auth\LoginController@verify');
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');
Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

Route::group([
	'prefix' => 'adverts',
	'as' => 'adverts.',
	'namespace' => 'Adverts',
], function () {
	Route::get('/show/{advert}', 'AdvertController@show')->name('show');
	Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
	Route::post('/show/{advert}/favorites', 'FavoriteController@add')->name('favorites');
	Route::delete('/show/{advert}/favorites', 'FavoriteController@remove');
	Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
            Route::post('/phone', 'PhoneController@request');
            Route::get('/phone', 'PhoneController@form')->name('phone');
            Route::put('/phone', 'PhoneController@verify')->name('phone.verify');
            Route::post('/phone/auth/', 'PhoneController@auth')->name('phone.auth');
        });
        Route::get('favorites', 'FavoriteController@index')->name('favorites.index');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
        Route::group([
            'prefix' => 'adverts',
            'as' => 'adverts.',
            'namespace' => 'Adverts',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'AdvertController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
            Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
            Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
            Route::put('/{advert}/edit', 'ManageController@edit');
            Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
            Route::post('/{advert}/photos', 'ManageController@photos');
            Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
            Route::post('/{advert}/attributes', 'ManageController@attributes');
            Route::post('/{advert}/send', 'ManageController@send')->name('send');
            Route::post('/{advert}/close', 'ManageController@close')->name('close');
            Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
        });
        Route::group([
            'prefix' => 'banners',
            'as' => 'banners.',
            'namespace' => 'Banners',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'BannerController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/banner/{category}/{region?}', 'CreateController@banner')->name('create.banner');
            Route::post('/create/banner/{category}/{region?}', 'CreateController@store')->name('create.banner.store');
            Route::get('/show/{banner}', 'BannerController@show')->name('show');
            Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
            Route::put('/{banner}/edit', 'BannerController@edit');
            Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
            Route::put('/{banner}/file', 'BannerController@file');
            Route::post('/{banner}/send', 'BannerController@send')->name('send');
            Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
            Route::post('/{banner}/order', 'BannerController@order')->name('order');
            Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
        });
    }
);

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'can:admin-panel'],
	],
	function () {
		Route::post('/ajax/upload/image', 'UploadController@image')->name('ajax.upload.image');
		Route::get('/', 'HomeController@index')->name('home');
		Route::resource('users', 'UsersController');
		Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
		Route::resource('regions', 'RegionController');
		Route::resource('pages', 'PageController');
		Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
			Route::post('/first', 'PageController@first')->name('first');
			Route::post('/up', 'PageController@up')->name('up');
			Route::post('/down', 'PageController@down')->name('down');
			Route::post('/last', 'PageController@last')->name('last');
		});
		Route::group(['prefix' => 'adverts', 'as' => 'adverts.', 'namespace' => 'Adverts'], function () {
			Route::resource('categories', 'CategoryController');
			Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
				Route::post('/first', 'CategoryController@first')->name('first');
				Route::post('/up', 'CategoryController@up')->name('up');
				Route::post('/down', 'CategoryController@down')->name('down');
				Route::post('/last', 'CategoryController@last')->name('last');
				Route::resource('attributes', 'AttributeController')->except('index');
			});
			Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
				Route::get('/', 'AdvertController@index')->name('index');
				Route::get('/{advert}/edit', 'AdvertController@editForm')->name('edit');
				Route::put('/{advert}/edit', 'AdvertController@edit');
				Route::get('/{advert}/photos', 'AdvertController@photosForm')->name('photos');
				Route::post('/{advert}/photos', 'AdvertController@photos');
				Route::get('/{advert}/attributes', 'AdvertController@attributesForm')->name('attributes');
				Route::post('/{advert}/attributes', 'AdvertController@attributes');
				Route::post('/{advert}/moderate', 'AdvertController@moderate')->name('moderate');
				Route::get('/{advert}/reject', 'AdvertController@rejectForm')->name('reject');
				Route::post('/{advert}/reject', 'AdvertController@reject');
				Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
			});
		});
		Route::group(['prefix' => 'banners', 'as' => 'banners.'], function () {
			Route::get('/', 'BannerController@index')->name('index');
			Route::get('/{banner}/show', 'BannerController@show')->name('show');
			Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
			Route::put('/{banner}/edit', 'BannerController@edit');
			Route::post('/{banner}/moderate', 'BannerController@moderate')->name('moderate');
			Route::get('/{banner}/reject', 'BannerController@rejectForm')->name('reject');
			Route::post('/{banner}/reject', 'BannerController@reject');
			Route::post('/{banner}/pay', 'BannerController@pay')->name('pay');
			Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
		});
		Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
			Route::get('/', 'TicketController@index')->name('index');
			Route::get('/{ticket}/show', 'TicketController@show')->name('show');
			Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
			Route::put('/{ticket}/edit', 'TicketController@edit');
			Route::post('{ticket}/message', 'TicketController@message')->name('message');
			Route::post('/{ticket}/close', 'TicketController@close')->name('close');
			Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
			Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
			Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
		});
	}
);

Route::get('/ajax/regions', 'Ajax\RegionController@get')->name('ajax.regions');

app/Http/Controllers/Admin/Adverts/AdvertController.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

use App\Http\Requests\Admin\RejectRequest;
use App\Http\Requests\Advert\EditRequest;
use App\Http\Requests\Cabinet\Advert\AttributesRequest;
use App\Models\Adverts\Advert\Advert;
use App\Http\Controllers\Controller;
use App\Http\Requests\Adverts\PhotosRequest;
use App\Models\User;
use App\UseCases\Adverts\AdvertService;
use Illuminate\Http\Request;

class AdvertController extends Controller
{
	use AdvertFilter;
	private $service;
	
	public function __construct(AdvertService $service)
	{
		$this->service = $service;
		$this->middleware('can:manage-adverts');
	}
	
	public function index(Request $request)
	{
		$query = Advert::orderByDesc('updated_at');
		$adverts = $this->filter($request, $query);
		$statuses = Advert::statusesList();
		$roles = User::rolesList();
		
		return view('admin.adverts.adverts.index', compact('adverts', 'statuses', 'roles'));
	}
	
	public function editForm(Advert $advert)
	{
		return view('adverts.edit.advert', compact('advert'));
	}
	
	public function edit(EditRequest $request, Advert $advert)
	{
		try {
			$this->service->edit($advert->id, $request);
		} catch (\DomainException $e) {
			return back()->with('error', $e->getMessage());
		}
		
		return redirect()->route('adverts.show', $advert);
	}
	
	public function attributesForm(Advert $advert)
	{
		return view('adverts.edit.attributes', compact('advert'));
	}
	
	public function attributes(AttributesRequest $request, Advert $advert)
	{
		try {
			$this->service->editAttributes($advert->id, $request);
		} catch (\DomainException $e) {
			return back()->with('error', $e->getMessage());
		}
		
		return redirect()->route('adverts.show', $advert);
	}
	
	public function photosForm(Advert $advert)
	{
		return view('adverts.edit.photos', compact('advert'));
	}
	
	public function photos(PhotosRequest $request, Advert $advert)
	{
		try {
			$this->service->addPhotos($advert->id, $request);
		} catch (\DomainException $e) {
			return back()->with('error', $e->getMessage());
		}
		
		return redirect()->route('adverts.show', $advert);
	}
	
	public function moderate(Advert $advert)
	{
		try {
			$this->service->moderate($advert->id);
		} catch (\DomainException $e) {
			return back()->with('error', $e->getMessage());
		}
		
		return redirect()->route('adverts.show', $advert);
	}
	
	public function rejectForm(Advert $advert)
	{
		return view('admin.adverts.adverts.reject', compact('advert'));
	}
	
	public function reject(RejectRequest $request, Advert $advert)
	{
		try {
			$this->service->reject($advert->id, $request);
		} catch (\DomainException $e) {
			return back()->with('error', $e->getMessage());
		}
		
		return redirect()->route('adverts.show', $advert);
	}
	
	public function destroy(Advert $advert)
	{
		try {
			$this->service->remove($advert->id);
		} catch (\DomainException $e) {
			return back()->with('error', $e->getMessage());
		}
		
		return redirect()->route('admin.adverts.adverts.index');
	}
}

app/Http/Controllers/Admin/Adverts/AdvertFilter.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

trait AdvertFilter
{
public function filter($request, $query)
{
	if (!empty($value = $request->get('id'))) {
		$query->where('id', $value);
	}
	if (!empty($value = $request->get('title'))) {
		$query->where('title', 'like', '%' . $value . '%');
	}
	if (!empty($value = $request->get('user'))) {
		$query->where('user_id', $value);
	}
	if (!empty($value = $request->get('region'))) {
		$query->where('region_id', $value);
	}
	if (!empty($value = $request->get('category'))) {
		$query->where('category_id', $value);
	}
	if (!empty($value = $request->get('status'))) {
		$query->where('status', $value);
	}
	if (!empty($value = $request->get('name'))) {
		$query->where('name', 'like', '%' . $value . '%');
	}
	if (!empty($value = $request->get('email'))) {
		$query->where('email', 'like', '%' . $value . '%');
	}
	if (!empty($value = $request->get('status'))) {
		$query->where('status', $value);
	}
	if (!empty($value = $request->get('role'))) {
		$query->where('role', $value);
	}
	
	return $query->paginate(20);
}
}

app/Http/Controllers/Admin/Adverts/AttributeController.php
<?php

namespace App\Http\Controllers\Admin\Adverts;

use App\Http\Requests\Admin\Adverts\AttributeRequest;
use App\Models\Adverts\Attribute;
use App\Models\Adverts\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;


class AttributeController extends Controller
{
    
    public function create(Category $category)
    {
        $types = Attribute::typesList();
        
        return view('admin.adverts.categories.attributes.create', compact('category', 'types'));
    }
    
    public function store(AttributeRequest $request, Category $category)
    {
        $attribute = $category->attributes()->create([
            'name' => $request['name'],
            'type' => $request['type'],
            'required' => (bool)$request['required'],
            'variants' => array_map('trim', preg_split('#[\r\n]+#', $request['variants'])),
            'sort' => $request['sort']
        ]);
        return redirect()->route('admin.adverts.categories.attributes.show', [$category, $attribute]);
    }
    
    public function show(Category $category, Attribute $attribute)
    {
        $types = Attribute::typesList();
        
        return view('admin.adverts.categories.attributes.edit', compact('category', 'attribute', 'types'));
    }
    
    public function edit(Category $category)
    {
        $parents = Category::defaultOrder()->withDepth()->get();
        
        return view('admin.adverts.categories.edit', compact('category', 'parents'));
    }
    
    public function update(AttributeRequest $request, Category $category, Attribute $attribute)
    {
        $category->attributes()->findOrFail($attribute->id)->update([
            'name' => $request['name'],
            'type' => $request['type'],
            'required' => (bool)$request['required'],
            'variants' => array_map('trim', preg_split('#[\r\n]+#', $request['variants'])),
            'sort' => $request['sort']
        ]);
        
        return redirect()->route('admin.adverts.categories.show', $category);
    }
    
    public function destroy(Category $category)
    {
        $category->delete();
        
        return redirect()->route('admin.adverts.categories.index');
    }
}

app/Http/Controllers/Adverts/AdvertController.php
<?php

namespace App\Http\Controllers\Adverts;

use App\Http\Router\AdvertsPath;
use App\Models\Adverts\Advert\Advert;
use App\Models\Adverts\Category;
use App\Models\Region;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Gate;

class AdvertController extends Controller
{
    public function index(AdvertsPath $path)
    {
	    $query = Advert::active()->with(['category', 'region'])->orderBy('published_at');

	    if ($category = $path->category) {
	    	$query->forCategory($category);
	    }
	
	    if ($region = $path->region) {
		    $query->forRegion($region);
	    }
	    
	    $regions = $region
		    ? $region->children()->orderBy('name')->getModels()
		    : Region::roots()->orderBy('name')->getModels();
	    
	    $categories = $category
		    ? $category->children()->defaultOrder()->getModels()
	        : Category::whereIsRoot()->defaultOrder()->getModels();
        
        $adverts = $query->paginate(20);
        
        return view('adverts.index', compact('category', 'region', 'regions', 'categories', 'adverts'));
    }
    
    public function show(Advert $advert)
    {
    	if (!($advert->isActive() || Gate::allows('show-advert', $advert))) {
    		abort(403);
	    }
	    $user = Auth::user();
    	
	    return view('adverts.show', compact('advert', 'user'));
    }
	
	public function phone(Advert $advert)
	{
		if (!($advert->isActive() || Gate::allows('show-advert', $advert))) {
			abort(403);
		}
		
		return $advert->user->phone;
	}
}

app/Http/Controllers/Cabinet/Adverts/AdvertController.php
<?php

namespace App\Http\Controllers\Cabinet\Adverts;

use App\Http\Middleware\FilledProfile;
use App\Models\Adverts\Advert\Advert;
use Auth;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdvertController extends Controller
{
	
	public function __construct()
	{
		$this->middleware(FilledProfile::class);
	}
	
	public function index()
    {
    	$adverts = Advert::forUser(Auth::user())->orderByDesc('id')->paginate(20);
    	
        return view('cabinet.adverts.index', compact('adverts'));
    }
}

resources/views/adverts/show.blade.php
@extends('layouts.app')

@section('content')
    
    @if ($advert->isDraft())
        <div class="alert alert-danger">
            It is a draft.
        </div>
        @if ($advert->reject_reason)
            <div class="alert alert-danger">
                {{ $advert->reject_reason }}
            </div>
        @endif
    @endif
    
    @can ('moderate-advert')
        <div class="d-flex flex-row mb-3">
            <a href="{{ route('admin.adverts.adverts.edit', $advert) }}" class="btn btn-primary mr-1">Edit</a>
            <a href="{{ route('admin.adverts.adverts.photos', $advert) }}" class="btn btn-primary mr-1">Photos</a>
            
            @if ($advert->isOnModeration())
                <form method="POST" action="{{ route('admin.adverts.adverts.moderate', $advert) }}" class="mr-1">
                    @csrf
                    <button class="btn btn-success">Moderate</button>
                </form>
            @endif
            
            @if ($advert->isOnModeration() || $advert->isActive())
                <a href="{{ route('admin.adverts.adverts.reject', $advert) }}" class="btn btn-danger mr-1">Reject</a>
            @endif
            
            <form method="POST" action="{{ route('admin.adverts.adverts.destroy', $advert) }}" class="mr-1">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Delete</button>
            </form>
        </div>
    @endcan
    
    @can ('manage-own-advert', $advert)
        <div class="d-flex flex-row mb-3">
            <a href="{{ route('cabinet.adverts.edit', $advert) }}" class="btn btn-primary mr-1">Edit</a>
            <a href="{{ route('cabinet.adverts.photos', $advert) }}" class="btn btn-primary mr-1">Photos</a>
            
            @if ($advert->isDraft())
                <form method="POST" action="{{ route('cabinet.adverts.send', $advert) }}" class="mr-1">
                    @csrf
                    <button class="btn btn-success">Publish</button>
                </form>
            @endif
            @if ($advert->isActive())
                <form method="POST" action="{{ route('cabinet.adverts.close', $advert) }}" class="mr-1">
                    @csrf
                    <button class="btn btn-success">Close</button>
                </form>
            @endif
            
            <form method="POST" action="{{ route('cabinet.adverts.destroy', $advert) }}" class="mr-1">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Delete</button>
            </form>
        </div>
    @endcan
    
    <div class="row">
        <div class="col-md-9">
            
            <p class="float-right" style="font-size: 36px;">{{ $advert->price }}</p>
            <h1 style="margin-bottom: 10px">{{ $advert->title  }}</h1>
            <p>
                @if ($advert->expires_at)
                    Date: {{ $advert->published_at }} &nbsp;
                @endif
                @if ($advert->expires_at)
                    Expires: {{ $advert->expires_at }}
                @endif
            </p>
            
            <div style="margin-bottom: 20px">
                <div class="row">
                    <div class="col-10">
                        <div style="height: 400px; background: #f6f6f6; border: 1px solid #ddd"></div>
                    </div>
                    <div class="col-2">
                        <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                        <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                        <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                        <div style="height: 100px; background: #f6f6f6; border: 1px solid #ddd"></div>
                    </div>
                </div>
            </div>
            
            <p>{!! nl2br(e($advert->content)) !!}</p>
            
            <table class="table table-bordered">
                <tbody>
                @foreach ($advert->category->allAttributes() as $attribute)
                    <tr>
                        <th>{{ $attribute->name }}</th>
                        <td>{{ $advert->getValue($attribute->id) }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
            
            <p>Address: {{ $advert->address }}</p>
            
            <div style="margin: 20px 0; border: 1px solid #ddd">
                <div id="map" style="width: 100%; height: 250px"></div>
            </div>
            
            <p style="margin-bottom: 20px">Seller: {{ $advert->user->name }}</p>
    
            <div class="d-flex flex-row mb-3">
                <span class="btn btn-success mr-1"><span class="fa fa-envelope"></span> Send Message</span>
                <span class="btn btn-primary phone-button mr-1" data-source="{{ route('adverts.phone', $advert) }}"><span class="fa fa-phone"></span> <span class="number">Show Phone Number</span></span>
                @if ($user && $user->hasInFavorites($advert->id))
                    <form method="POST" action="{{ route('adverts.favorites', $advert) }}" class="mr-1">
                        @csrf
                        @method('DELETE')
                        <button class="btn btn-secondary"><span class="fa fa-star"></span> Remove from Favorites</button>
                    </form>
                @else
                    <form method="POST" action="{{ route('adverts.favorites', $advert) }}" class="mr-1">
                        @csrf
                        <button class="btn btn-danger"><span class="fa fa-star"></span> Add to Favorites</button>
                    </form>
                @endif
            </div>
            
            <hr/>
            
            <div class="h3">Similar adverts</div>
            
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb" alt=""/>
                        <div class="card-body">
                            <div class="card-title h4 mt-0" style="margin: 10px 0"><a href="#">The First Thing</a></div>
                            <p class="card-text" style="color: #666">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb" alt=""/>
                        <div class="card-body">
                            <div class="card-title h4 mt-0" style="margin: 10px 0"><a href="#">The First Thing</a></div>
                            <p class="card-text" style="color: #666">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 col-md-4">
                    <div class="card">
                        <img class="card-img-top" src="https://images.pexels.com/photos/297933/pexels-photo-297933.jpeg?w=1260&h=750&auto=compress&cs=tinysrgb" alt=""/>
                        <div class="card-body">
                            <div class="card-title h4 mt-0" style="margin: 10px 0"><a href="#">The First Thing</a></div>
                            <p class="card-text" style="color: #666">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                        </div>
                    </div>
                </div>
            </div>
        
        </div>
        <div class="col-md-3">
            <div style="height: 400px; background: #f6f6f6; border: 1px solid #ddd; margin-bottom: 20px"></div>
            <div style="height: 400px; background: #f6f6f6; border: 1px solid #ddd; margin-bottom: 20px"></div>
        </div>
    </div>
@endsection

@section('scripts')
    
    <script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
    
    <script type='text/javascript'>
        ymaps.ready(init);
        function init(){
            var geocoder = new ymaps.geocode(
                // Строка с адресом, который нужно геокодировать
                '{{ $advert->address }}',
                // требуемое количество результатов
                { results: 1 }
            );
            // После того, как поиск вернул результат, вызывается callback-функция
            geocoder.then(
                function (res) {
                    // координаты объекта
                    var coord = res.geoObjects.get(0).geometry.getCoordinates();
                    var map = new ymaps.Map('map', {
                        // Центр карты - координаты первого элемента
                        center: coord,
                        // Коэффициент масштабирования
                        zoom: 7,
                        // включаем масштабирование карты колесом
                        behaviors: ['default', 'scrollZoom'],
                        controls: ['mapTools']
                    });
                    // Добавление метки на карту
                    map.geoObjects.add(res.geoObjects.get(0));
                    // устанавливаем максимально возможный коэффициент масштабирования - 1
                    map.zoomRange.get(coord).then(function(range){
                        map.setCenter(coord, range[1] - 1)
                    });
                    // Добавление стандартного набора кнопок
                    map.controls.add('mapTools')
                    // Добавление кнопки изменения масштаба
                        .add('zoomControl')
                        // Добавление списка типов карты
                        .add('typeSelector');
                }
            );
        }
    </script>
@endsection