routes/web.php
<?php

Route::get('/', 'HomeController@index')->name('home');

Auth::routes();
Route::get('/login/phone', 'Auth\LoginController@phone')->name('login.phone');
Route::post('/login/phone', 'Auth\LoginController@verify');
Route::get('/verify/{token}', 'Auth\RegisterController@verify')->name('register.verify');
Route::get('/login/{network}', 'Auth\NetworkController@redirect')->name('login.network');
Route::get('/login/{network}/callback', 'Auth\NetworkController@callback');

Route::group([
	'prefix' => 'adverts',
	'as' => 'adverts.',
	'namespace' => 'Adverts',
], function () {
	Route::get('/show/{advert}', 'AdvertController@show')->name('show');
	Route::post('/show/{advert}/phone', 'AdvertController@phone')->name('phone');
	Route::post('/show/{advert}/favorites', 'FavoriteController@add')->name('favorites');
	Route::delete('/show/{advert}/favorites', 'FavoriteController@remove');
	Route::get('/{adverts_path?}', 'AdvertController@index')->name('index')->where('adverts_path', '.+');
});

Route::group(
    [
        'prefix' => 'cabinet',
        'as' => 'cabinet.',
        'namespace' => 'Cabinet',
        'middleware' => ['auth'],
    ],
    function () {
        Route::get('/', 'HomeController@index')->name('home');
        Route::group(['prefix' => 'profile', 'as' => 'profile.'], function () {
            Route::get('/', 'ProfileController@index')->name('home');
            Route::get('/edit', 'ProfileController@edit')->name('edit');
            Route::put('/update', 'ProfileController@update')->name('update');
            Route::post('/phone', 'PhoneController@request');
            Route::get('/phone', 'PhoneController@form')->name('phone');
            Route::put('/phone', 'PhoneController@verify')->name('phone.verify');
            Route::post('/phone/auth/', 'PhoneController@auth')->name('phone.auth');
        });
        Route::get('favorites', 'FavoriteController@index')->name('favorites.index');
        Route::delete('favorites/{advert}', 'FavoriteController@remove')->name('favorites.remove');
        Route::resource('tickets', 'TicketController')->only(['index', 'show', 'create', 'store', 'destroy']);
        Route::post('tickets/{ticket}/message', 'TicketController@message')->name('tickets.message');
        Route::group([
            'prefix' => 'adverts',
            'as' => 'adverts.',
            'namespace' => 'Adverts',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'AdvertController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/advert/{category}/{region?}', 'CreateController@advert')->name('create.advert');
            Route::post('/create/advert/{category}/{region?}', 'CreateController@store')->name('create.advert.store');
            Route::get('/{advert}/edit', 'ManageController@editForm')->name('edit');
            Route::put('/{advert}/edit', 'ManageController@edit');
            Route::get('/{advert}/photos', 'ManageController@photosForm')->name('photos');
            Route::post('/{advert}/photos', 'ManageController@photos');
            Route::get('/{advert}/attributes', 'ManageController@attributesForm')->name('attributes');
            Route::post('/{advert}/attributes', 'ManageController@attributes');
            Route::post('/{advert}/send', 'ManageController@send')->name('send');
            Route::post('/{advert}/close', 'ManageController@close')->name('close');
            Route::delete('/{advert}/destroy', 'ManageController@destroy')->name('destroy');
        });
        Route::group([
            'prefix' => 'banners',
            'as' => 'banners.',
            'namespace' => 'Banners',
            'middleware' => [App\Http\Middleware\FilledProfile::class],
        ], function () {
            Route::get('/', 'BannerController@index')->name('index');
            Route::get('/create', 'CreateController@category')->name('create');
            Route::get('/create/region/{category}/{region?}', 'CreateController@region')->name('create.region');
            Route::get('/create/banner/{category}/{region?}', 'CreateController@banner')->name('create.banner');
            Route::post('/create/banner/{category}/{region?}', 'CreateController@store')->name('create.banner.store');
            Route::get('/show/{banner}', 'BannerController@show')->name('show');
            Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
            Route::put('/{banner}/edit', 'BannerController@edit');
            Route::get('/{banner}/file', 'BannerController@fileForm')->name('file');
            Route::put('/{banner}/file', 'BannerController@file');
            Route::post('/{banner}/send', 'BannerController@send')->name('send');
            Route::post('/{banner}/cancel', 'BannerController@cancel')->name('cancel');
            Route::post('/{banner}/order', 'BannerController@order')->name('order');
            Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
        });
    }
);

Route::group(
	[
		'prefix' => 'admin',
		'as' => 'admin.',
		'namespace' => 'Admin',
		'middleware' => ['auth', 'can:admin-panel'],
	],
	function () {
		Route::post('/ajax/upload/image', 'UploadController@image')->name('ajax.upload.image');
		Route::get('/', 'HomeController@index')->name('home');
		Route::resource('users', 'UsersController');
		Route::post('/users/{user}/verify', 'UsersController@verify')->name('users.verify');
		Route::resource('regions', 'RegionController');
		Route::resource('pages', 'PageController');
		Route::group(['prefix' => 'pages/{page}', 'as' => 'pages.'], function () {
			Route::post('/first', 'PageController@first')->name('first');
			Route::post('/up', 'PageController@up')->name('up');
			Route::post('/down', 'PageController@down')->name('down');
			Route::post('/last', 'PageController@last')->name('last');
		});
		Route::group(['prefix' => 'adverts', 'as' => 'adverts.', 'namespace' => 'Adverts'], function () {
			Route::resource('categories', 'CategoryController');
			Route::group(['prefix' => 'categories/{category}', 'as' => 'categories.'], function () {
				Route::post('/first', 'CategoryController@first')->name('first');
				Route::post('/up', 'CategoryController@up')->name('up');
				Route::post('/down', 'CategoryController@down')->name('down');
				Route::post('/last', 'CategoryController@last')->name('last');
				Route::resource('attributes', 'AttributeController')->except('index');
			});
			Route::group(['prefix' => 'adverts', 'as' => 'adverts.'], function () {
				Route::get('/', 'AdvertController@index')->name('index');
				Route::get('/{advert}/edit', 'AdvertController@editForm')->name('edit');
				Route::put('/{advert}/edit', 'AdvertController@edit');
				Route::get('/{advert}/photos', 'AdvertController@photosForm')->name('photos');
				Route::post('/{advert}/photos', 'AdvertController@photos');
				Route::get('/{advert}/attributes', 'AdvertController@attributesForm')->name('attributes');
				Route::post('/{advert}/attributes', 'AdvertController@attributes');
				Route::post('/{advert}/moderate', 'AdvertController@moderate')->name('moderate');
				Route::get('/{advert}/reject', 'AdvertController@rejectForm')->name('reject');
				Route::post('/{advert}/reject', 'AdvertController@reject');
				Route::delete('/{advert}/destroy', 'AdvertController@destroy')->name('destroy');
			});
		});
		Route::group(['prefix' => 'banners', 'as' => 'banners.'], function () {
			Route::get('/', 'BannerController@index')->name('index');
			Route::get('/{banner}/show', 'BannerController@show')->name('show');
			Route::get('/{banner}/edit', 'BannerController@editForm')->name('edit');
			Route::put('/{banner}/edit', 'BannerController@edit');
			Route::post('/{banner}/moderate', 'BannerController@moderate')->name('moderate');
			Route::get('/{banner}/reject', 'BannerController@rejectForm')->name('reject');
			Route::post('/{banner}/reject', 'BannerController@reject');
			Route::post('/{banner}/pay', 'BannerController@pay')->name('pay');
			Route::delete('/{banner}/destroy', 'BannerController@destroy')->name('destroy');
		});
		Route::group(['prefix' => 'tickets', 'as' => 'tickets.'], function () {
			Route::get('/', 'TicketController@index')->name('index');
			Route::get('/{ticket}/show', 'TicketController@show')->name('show');
			Route::get('/{ticket}/edit', 'TicketController@editForm')->name('edit');
			Route::put('/{ticket}/edit', 'TicketController@edit');
			Route::post('{ticket}/message', 'TicketController@message')->name('message');
			Route::post('/{ticket}/close', 'TicketController@close')->name('close');
			Route::post('/{ticket}/approve', 'TicketController@approve')->name('approve');
			Route::post('/{ticket}/reopen', 'TicketController@reopen')->name('reopen');
			Route::delete('/{ticket}/destroy', 'TicketController@destroy')->name('destroy');
		});
	}
);

Route::get('/ajax/regions', 'Ajax\RegionController@get')->name('ajax.regions');

app/Models/User/Network.php
<?php

namespace App\Models\User;
use Illuminate\Database\Eloquent\Model;

/**
 * @property int $user_id
 * @property string $network
 * @property string $identity
 */
class Network extends Model
{
	protected $table = 'user_networks';
	protected $fillable = ['network', 'identity'];
	public $timestamps = false;
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Admin\Adverts\AdvertFilter;
use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Hash;
use Illuminate\Validation\Rule;

class UsersController extends Controller
{
	use AdvertFilter;
	
	public function index(Request $request)
	{
		$query = User::orderByDesc('id');
		$users = $this->filter($request, $query);
		$statuses = [
			User::STATUS_WAIT => 'Waiting',
			User::STATUS_ACTIVE => 'Active',
		];
		$roles = User::rolesList();
		return view('admin.users.index', compact('users', 'statuses', 'roles'));
	}
    
    public function create()
    {
        return view('admin.users.create');
    }
    
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
        ]);
        
        $user = User::create([
            'name' => $request[ 'name' ],
            'email' => $request[ 'email' ],
            'status' => User::STATUS_ACTIVE,
            'password' => Hash::make('password')
        ]);
        
        return redirect()->route('admin.users.show', $user);
    }
    
    public function show(User $user)
    {
        return view('admin.users.show', compact('user'));
    }
    
    public function edit(User $user)
    {
        $statuses = [
            User::STATUS_ACTIVE => 'Active',
            User::STATUS_WAIT => 'Waiting'
        ];
    
        $roles = User::rolesList();
        
        return view('admin.users.edit', compact('user', 'statuses', 'roles'));
    }
    
    public function update(Request $request, User $user)
    {
        $data = $this->validate($request, [
            'name' => 'required', 'string', 'max:255',
            'email' => 'required', 'string', 'email', 'max:255', 'unique:users',
            'status' => 'required', 'string', Rule::in(User::STATUS_WAIT, User::STATUS_ACTIVE),
            'role' => 'required', 'string', Rule::in(User::ROLE_USER, User::ROLE_ADMIN)
        ]);
        //TODO сделать редактирование статуса для юзера
        $user->update($data);
        
        return redirect()->route('admin.users.show', $user);
    }
    
    public function destroy(User $user)
    {
        $user->delete();
    
        return redirect()->route('admin.users.index', $user);
    }
}

app/Http/Controllers/Api/User/ProfileController.php
<?php

namespace App\Http\Controllers\Api\User;

use App\Models\User;
use App\Http\Controllers\Controller;
use App\Http\Requests\Auth\ProfileEditRequest;
use App\Http\Resources\User\ProfileResource;
use App\UseCases\Profile\ProfileService;
use Illuminate\Http\Request;

class ProfileController extends Controller
{
    private $service;
    
    public function __construct(ProfileService $service)
    {
        $this->service = $service;
    }
    
    public function index(Request $request)
    {
        $users = User::all();
        return ProfileResource::collection($users);
    }
    
    /**
     * @SWG\Get(
     *     path="/user",
     *     tags={"Profile"},
     *     @SWG\Response(
     *         response=200,
     *         description="Success response",
     *         @SWG\Schema(ref="#/definitions/Profile"),
     *     ),
     *     security={{"Bearer": {}, "OAuth2": {}}}
     * )
     */
    public function show(Request $request)
    {
        return new ProfileResource($request->user());
    }
    
    /**
     * @SWG\Put(
     *     path="/user",
     *     tags={"Profile"},
     *     @SWG\Parameter(name="body", in="body", required=true, @SWG\Schema(ref="#/definitions/ProfileEditRequest")),
     *     @SWG\Response(
     *         response=200,
     *         description="Success response",
     *     ),
     *     security={{"Bearer": {}, "OAuth2": {}}}
     * )
     */
    public function update(ProfileEditRequest $request)
    {
        $this->service->edit($request->user()->id, $request);
        
        $user = User::findOrFail($request->user()->id);
        return new ProfileResource($user);
    }
}

resources/views/admin/users/_nav.blade.php
<ul class="nav nav-tabs md-3">
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.home') }}">Dashboard</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="{{ route('admin.users.index') }}">Users</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.regions.index') }}">Regions</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ route('admin.adverts.categories.index') }}">Category</a>
    </li>
</ul>

resources/views/admin/users/create.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <form method="POST" action="{{ route('admin.users.store') }}">
        @csrf
    
        <div class="form-group">
            <label for="" class="col-form-label">Name</label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
            name="name" value="{{ old('name') }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
    
        <div class="form-group">
            <label for="" class="col-form-label">Email</label>
            <input id="email" type="email" class="form-control{{ $errors->has('email') ? ' is-invalid' : '' }}"
                   name="email" value="{{ old('email') }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong>
                </span>
            @endif
        </div>
    
        <div class="form-group">
            <button class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/edit.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')
    
    <form method="POST" action="{{ route('admin.users.update', $user) }}">
        @csrf
        @method('PUT')
        
        <div class="form-group">
            <label for="" class="col-form-label">Name</label>
            <input id="name" type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}"
                   name="name" value="{{ old('name', $user->name) }}" required>
            @if ($errors->has('name'))
                <span class="invalid-feedback"><strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>
        
        <div class="form-group">
            <label for="" class="col-form-label">Email</label>
            <input id="email" type="email" class="form-control {{ $errors->has('email') ? 'is-invalid' : '' }}"
                   name="email" value="{{ old('email', $user->email) }}" required>
            @if ($errors->has('email'))
                <span class="invalid-feedback"><strong>{{ $errors->first('email') }}</strong></span>
            @endif
        </div>
    
        <div class="form-group">
            <label for="status" class="col-form-label">Status</label>
            <select name="status" id="status" class="form-control {{ $errors->has('status') ? ' is-invalid' : '' }}">
                @foreach($statuses as $value => $label)
                    <option value="{{ $value }}" {{ $value === old('status', $user->status) ? 'selected' : '' }}>
                        {{ $label }}
                    </option>
                @endforeach
            </select>
            @if ($errors->has('status'))
                <span class="invalid-feedback"><strong>{{ $errors->first('status') }}</strong></span>
            @endif
        </div>
    
        <div class="form-group">
            <label for="status" class="col-form-label">ROLE</label>
            <select name="role" id="role" class="form-control {{ $errors->has('role') ? ' is-invalid' : '' }}">
                @foreach($roles as $value => $label)
                    <option value="{{ $value }}" {{ $value === old('role', $user->role) ? 'selected' : '' }}>
                        {{ $label }}
                    </option>
                @endforeach
            </select>
            @if ($errors->has('role'))
                <span class="invalid-feedback"><strong>{{ $errors->first('role') }}</strong></span>
            @endif
        </div>
        
        <div class="form-group">
            <button class="btn btn-primary">Save</button>
        </div>
    </form>
@endsection

resources/views/admin/users/index.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')

    <p><a href="{{ route('admin.users.create') }}" class="btn btn-success mr-1 mt-3">Add user</a></p>

    <div class="card mb-3">
        <div class="card-header">Filter</div>
        <div class="card-body">
            <form action="?" method="get">
                <div class="row">
                    <div class="col-sm-1">
                        <div class="form-group">
                            <label for="id" class="col-form-label">ID</label>
                            <input type="text" id="id" class="form-control" name="id" value="{{ request('id') }}">
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            <label for="name" class="col-form-label">Name</label>
                            <input type="text" id="name" class="form-control" name="name" value="{{ request('name') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="email" class="col-form-label">Email</label>
                            <input type="text" id="email" class="form-control" name="email" value="{{ request('email') }}">
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="status" class="col-form-label">Status</label>
                            <select id="status" name="status" class="form-control">
                                <option value=""></option>
                                @foreach ($statuses as $value => $label) {
                                <option value="{{ $value }}" {{ $value === request('status') ? 'selected' : ''}}>
                                    {{ $label }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label for="role" class="col-form-label">Role</label>
                            <select id="role" name="role" class="form-control">
                                <option value=""></option>
                                @foreach ($roles as $value => $label)
                                <option value="{{ $value }}" {{ $value === request('status') ? 'selected' : ''}}>
                                    {{ $label }}
                                </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="form-group">
                            <label class="col-form-label">&nbsp;</label><br>
                            <button class="btn btn-primary" type="submit">Search</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
    
    
    <table class="table table-bordered table-striped">
        <thead>
        <tr>
            <th>ID</th>
            <th>NAME</th>
            <th>EMAIL</th>
            <th>STATUS</th>
            <th>ROLE</th>
        </tr>
        </thead>
        <tbody>
        
        @foreach($users as $user)
            <tr>
                <td>{{ $user->id }}</td>
                <td><a href="{{ route('admin.users.show', $user) }}">{{ $user->name }}</a></td>
                <td>{{ $user->email }}</td>
                <td>
                    @if ($user->isWait())
                        <span class="badge badge-secondary">Waiting</span>
                    @endif
                    @if ($user->isActive())
                        <span class="badge badge-primary">Active</span>
                    @endif
                </td>
                <td>
                    @if ($user->isAdmin())
                        <span class="badge badge-danger">Admin</span>
                    @else
                        <span class="badge badge-secondary">User</span>
                    @endif
                    
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

    {{ $users->links() }}
@endsection

resources/views/admin/users/show.blade.php
@extends('layouts.app')

@section('content')
    @include('admin.users._nav')
    
    <div class="d-flex flex-row mb-3 mt-3">
        <a href="{{ route('admin.users.edit', $user) }}" class="btn btn-primary mr-1">Edit</a>
            <form method="POST" action="{{ route('admin.users.update', $user) }}" class="mr-1">
                @csrf
                @method('DELETE')
                <button class="btn btn-danger">Delete</button>
            </form>
    </div>
    
    <table class="table table-bordered table-striped">
        <tbody>
        <tr>
            <th>ID</th>
            <td>{{ $user->id }}</td>
        </tr>
        <tr>
            <th>NAME</th>
            <td>{{ $user->name }}</td>
        </tr>
        <tr>
            <th>EMAIL</th>
            <td>{{ $user->email }}</td>
        </tr>
        <tr>
            <th>STATUS</th>
            <td>@if ($user->status === \App\Models\User::STATUS_WAIT)
                    <span class="badge badge-secondary">Waiting</span>
                @endif
                @if ($user->status === \App\Models\User::STATUS_ACTIVE)
                    <span class="badge badge-primary">Active</span>
                @endif</td>
        </tr>
        <tr>
            <th>ROLE</th>
            <td>{{ $user->role }}</td>
        </tr>
        </tbody>
    </table>
@endsection